# Generated by Django 5.1.7 on 2025-05-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimodelo',
            name='categoria',
            field=models.CharField(choices=[('femenino', 'Femenino'), ('kids', 'Kids'), ('unica', 'Única')], default='femenino', max_length=20),
        ),
    ]
