# Generated by Django 5.1.7 on 2025-05-24 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_mimodelo_equipo_mimodelo_torneo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('posicion', models.CharField(blank=True, max_length=50, null=True)),
                ('equipo_fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='apps.mimodelo')),
            ],
        ),
    ]
